### ISSUE TITLE
Error     raise NodeNotFound

### ISSUE THREAD

**Issue by whoislimshady** [veryacademy/django-ecommerce-project#1]
![gh](https://user-images.githubusercontent.com/72891217/119224471-30f87600-bb1c-11eb-9202-7ba696d344bf.jpg)
 
i was following your tutorial i tried to download to the 3rd part code but it raise this error while running 
btw thanks your knowledge about django is awesome

**Comment by detectivevoke** [comment]
> ![gh](https://user-images.githubusercontent.com/72891217/119224471-30f87600-bb1c-11eb-9202-7ba696d344bf.jpg)
> 
> i was following your tutorial i tried to download to the 3rd part code but it raise this error while running btw thanks your knowledge about django is awesome

run python manage.py migrate --run-syncdb :)
